### ISSUE TITLE
Question about multimodal data

### ISSUE THREAD

**Issue by jacobhepkema** [alexandrotrevino/brainchromatin#1]
Hi Alexandro, very inspiring works! I was wondering if you were planning on sharing the multimodal data here too - could you please let me know?

**Comment by alexandrotrevino** [comment]
Hi Jacob! Thank you for your request. Your message actually made me realize
that I omitted the multiome data from the page. That was just an oversight
on my part... My apologies for that.  I should have the data up there by
the end of the day!

Best,
Alex

**Comment by alexandrotrevino** [comment]
you should be able to access now, email me if any issues

**Comment by jacobhepkema** [comment]
Thank you very much! :) 👍

**Comment by jacobhepkema** [comment]
Hi Alexandro, thank you again for sharing the data! I have one other question; would you be willing to share the peak locations of the multiome ATAC data? I think I've found the start and end locations of the peaks in the `rowData(sce)` but I couldn't find the chromosomes these locations are from. Sorry if it's already shared somewhere and I missed it

Best, 
Jacob

**Comment by alexandrotrevino** [comment]
Ahh, it should be there. I just tested it -- try:
rowRanges(sce)
or chromosome names directly:
seqnames(rowRanges(sce))
and do let me know if that doesn't work!

**Comment by jacobhepkema** [comment]
Thank you! Sorry - I wasn't familiar with `rowRanges` :)
