### ISSUE TITLE
Mismatch in multiome_cluster_names.txt

### ISSUE THREAD

**Issue by MagpiePKU** [alexandrotrevino/brainchromatin#10]
Hi,

Thanks for sharing the data. I noticed that in the paper (Figure 2) and the file `multiome_cluster_names.txt` does not exactly match. For example there are `nIPC/GluN1` as c8 in ATAC. 

As for the paper I was refering to `https://www.biorxiv.org/content/10.1101/2020.12.29.424636v2.full.pdf` Figure 2G. 

Thanks,
Yi

**Comment by alexandrotrevino** [comment]
Hi Yi,

I was able to fix minor typos in `multiome_cluster_names`. The file should be in line with Figure 2G in the final manuscript version (I can't guarantee it will match the preprint)

Thanks.
