### ISSUE TITLE
TF Enrichment linked peaks

### ISSUE THREAD

**Issue by waltno** [alexandrotrevino/brainchromatin#11]
Can you point me to or upload code for how you did TF motif enrichment in linked peaks? I see that you used motifmatchr and lola but can't find the code. Pic for reference
<img width="243" alt="Screen Shot 2022-04-08 at 1 48 09 PM" src="https://user-images.githubusercontent.com/94873838/162527907-2cc57a0b-6f98-447f-8888-a329e754c1c2.png">
e

**Comment by demuellae** [comment]
Hi,
Sorry, the exact code is not in the repository. But it can be easily implemented using the description in the methods section of the paper. Here are a few additional guides if you want to implement it yourself:
first, we fed TF motif occurrences identified using motifmatchr into a LOLA database and then used LOLA to conduct a hypergeometric test to quantify enrichment of the peak clusters that you see in the heatmap in Figure 3c. Then we used the resulting table from the LOLA output to create the dotplot that you posted using ggplot2. 
Hope that helps!
