### ISSUE TITLE
matching gene-cre link k-means clusters to annotated cell-types

### ISSUE THREAD

**Issue by naumanjaved** [alexandrotrevino/brainchromatin#13]
Hello!

Thanks for this wonderful resource. It was a little bit unclear to me how the reported link clusters(link cluster column of table S2A) relates to the annotated cell-types. For example in the paper it is stated that "Clustering the associated CRE accessibility revealed particularly high variability across clusters corresponding to glial cell populations, corroborated the distinctiveness of IN clusters, and indicated dynamic patterns of gene regulation across GluN clusters.". Is the mapping from CRE clusters to annotated cell-types available somewhere? 

Thanks so much!
Nauman

**Comment by alexandrotrevino** [comment]
Thank you for the question! If I understand your question correctly, you are asking about the methods underlying the big heatmap in Figure 2C. (excuse the bad screenshot)
![image](https://user-images.githubusercontent.com/17521123/202306468-356f5f51-abb8-4f6a-9db3-bf715d8e5ad7.png)

The relationship or is not actually explicit. When we say **"...clusters corresponding to,"** we mean, **"clusters whose member CREs are predominantly open in."** That is why you aren't going to find, e.g., another column in S2A! 

Happy to discuss avenues for associating them if you're interested, but yeah that particular mapping is just heuristic.

**Comment by naumanjaved** [comment]
Thanks so much for explaining, that makes sense
