### ISSUE TITLE
Fragments file availability for multiome?

### ISSUE THREAD

**Issue by cnk113** [alexandrotrevino/brainchromatin#2]
Hello,

I was wondering if it was possible to get fragments file from the cellranger-arc outputs for these datasets?
I'd like to run it through different pipelines that can accept fragment inputs.
Since the fragments files don't have any SNV information it should be fine to make it accessible to the public?

Thanks,
Chang

**Comment by alexandrotrevino** [comment]
Sure -added these to the links file.

**Comment by alhafidzhamdan** [comment]
Hi @alexandrotrevino,
I downloaded the fragment files and I'm not sure how you processed the 3 replicates? In the paper you said you merged them but it's not clear how you went about doing this. Could you please provide a description as to how you get to your final set of cell number  ie 8981?

**Comment by demuellae** [comment]
Hi,
we just combined the fragments from all replicates and filtered using ChrAccR. Filtering was done by removing cells with < 1000 fragments or > 100,000 fragments or a TSS Enrichment score < 4. This gave us 9,091 ATAC cells. We matched the cells with our filtered  Seurat dataset for RNA and 8981 cells were contained in both RNA and ATAC.
Hope that helps.

Fabian
