### ISSUE TITLE
multiome ATAC cluster annotation missing

### ISSUE THREAD

**Issue by alhafidzhamdan** [alexandrotrevino/brainchromatin#4]
Hi there,
I'm trying to process the scmultiome data, I noticed in the metadata that there is no ATAC cluster annotation, so I can't pair it with the cluster names txt file that you have provided. Am I missing something? 
Thanks for your help!
A

**Comment by alexandrotrevino** [comment]
That's odd! I have revised `multiome_cell_metadata.txt`. Please try to pull that file again.
