### ISSUE TITLE
failed to download Multiome CellRanger output folders

### ISSUE THREAD

**Issue by rdf1993** [alexandrotrevino/brainchromatin#5]
403 Forbidden

**Comment by alexandrotrevino** [comment]
Explicit prefixes and suffixes are now provided in `links.txt`. Can you try again? You will need to concatenate the prefix and suffix to retrieve the file with `wget` or similar.

**Comment by rdf1993** [comment]
It is still failed to download files in output folder while there is no problem for others.

wget https://atrev.s3.amazonaws.com/brainchromatin/hft_ctx_w21_dc2r2_r1/outs/atac_fragments.tsv.gz      8 ↵
--2021-10-14 18:49:33--  https://atrev.s3.amazonaws.com/brainchromatin/hft_ctx_w21_dc2r2_r1/outs/atac_fragments.tsv.gz
Resolving atrev.s3.amazonaws.com (atrev.s3.amazonaws.com)... 52.217.130.177
Connecting to atrev.s3.amazonaws.com (atrev.s3.amazonaws.com)|52.217.130.177|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-10-14 18:49:34 ERROR 403: Forbidden.

**Comment by alexandrotrevino** [comment]
Thanks for your patience. I modified permissions and verified that download is possible now from a remote source. Should be good to go, but I will keep open until you confirm.

**Comment by rdf1993** [comment]
Thank you. The problem had been solved.
