### ISSUE TITLE
The index file is older than the data file

### ISSUE THREAD

**Issue by rdf1993** [alexandrotrevino/brainchromatin#6]
The index file is older than the data file: hft_ctx_w21_dc1r3_r1_atac_fragments.tsv.gz.tbi
failed to open index file: hft_ctx_w21_dc1r3_r1_atac_fragments.tsv.gz.tbi

**Comment by alexandrotrevino** [comment]
These are redundant files given the whole multiome CR output folder is now included. I have removed them from `links.txt`. If there's another problem with CR output, it can go to the other thread.
