### ISSUE TITLE
Seurat Projection Encountered Issues

### ISSUE THREAD

**Issue by SammiLyu** [alexandrotrevino/brainchromatin#7]
Hello,

Thank you for sharing the datasets and they are really really helpful!
I am currently working on projecting my dataset to your scRNA UMAP through the Seurat pipeline (FindTransferAnchors and MapQuery). However, I cannot locate the feature loadings for PCA in "scRNA_SCE.RDS". Would you mind pointing to where in sce are the feature loadings stored? Really appreciate it!

Best,
Sammi

**Comment by alexandrotrevino** [comment]
Hi Sammi. I am terribly sorry for the slow reply. Do you mean this?
```pca <- reducedDims(rna)[["PCA"]]```
Alex

**Comment by alexandrotrevino** [comment]
Oh, I see. The feature loadings are missing, not the cell embeddings. Yes, it seems these were not preserved from Seurat to SingleCellExperiment. Good catch.

I have updated the SCE object `scRNA_SCE2.RDS` in the links.txt file. If you pull that, you should see both the cell embeddings and the feature loadings. They can be accessed with `reduedDims()` as above. `str(sce.object)` is a useful command for seeing how these S4 objects are structured. 

Let me know if there are further issues.

**Comment by SammiLyu** [comment]
Hi @alexandrotrevino, thank you so much for updating the SCE object!

I am not really sure if I should open up a new issue or keep replying to this one, please let me know if I should do otherwise.
What I was hoping to achieve was actually using Seurat package to map my data (query) to your data (reference), and to achieve that I would like to keep your UMAP structure intact. However, functions in Seurat (MapQuery for example) requires the umap model to achieve so and I could not locate it in your SCE object. Would this be something possible to share as well? Or is it already there and I might have overlooked it? Thank you so much!

**Comment by alexandrotrevino** [comment]
This is fine! I will verify where the model is, and if not present, I'll share it as well. Thanks for letting us know!

**Comment by alexandrotrevino** [comment]
FYI the Seurat object, and UMAP model, are now added in links. There is a script added as well to project a matrix into a Seurat object.

**Comment by SammiLyu** [comment]
Thank you so much for sharing the umap model and the script!

**Comment by Lindsey8383** [comment]
This is all great, thank you! Adding the appropriate link to links.txt (umapModel_rna_hft_uwot's link) and sourcing that file again results in the download of an executable file without a file extension ("umapModel_rna_hft_uwot") to the "tsv" folder. It doesn't seem to be a true executable file, though, as it errors out. I also cannot convert this to a tsv. Would you mind assisting me or re-uploading as a tsv, if that's the intention?

**Comment by demuellae** [comment]
It is not a tsv file, but a binary file of a UWOT model. It can be loaded in R using `uwot::load_uwot(...)` (https://rdrr.io/cran/uwot/man/load_uwot.html)
