### ISSUE TITLE
Pseudotime measurements for glutamatergic neurons

### ISSUE THREAD

**Issue by ryandhindsa** [alexandrotrevino/brainchromatin#8]
Hi Alexandro,

Thanks for such a clean repo! I can't seem to find the pseudotime inferences used for Fig 3A in the paper. Did you include the pseudotime measurements for glutamatergic neurons in any of the objects? I only was able to find it for the glial populations, but I may have missed something. 

Thanks
Ryan

**Comment by alexandrotrevino** [comment]
They should have been in the SCE object, but I have added them as `velocity_output.txt` to links.

**Comment by hongruhu** [comment]
hi @alexandrotrevino, I could not find the `velocity_output.txt`, is this file (https://atrev.s3.amazonaws.com/brainchromatin/velo_colData.txt) the same? If so, where could I get the corresponding barcode for each row? 
Thanks!
